# Generated by Django 3.2 on 2021-04-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_change', models.CharField(max_length=50)),
                ('change', models.TextField()),
                ('change_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ChangeLog',
                'verbose_name_plural': 'ChangeLogs',
            },
        ),
    ]
